; @file  pytest.ini
; @brief This file configures pytest for the project.
; - 'testpaths' sets the directory where tests are located.
; - 'pythonpath' adds the current directory to the Python path for test discovery.

[pytest]
testpaths = tests
pythonpath = .